export const INIT_RUN = "INIT_RUN"
export const JSON_VIDEO_DATA_SUCCESS = "JSON_VIDEO_DATA_SUCCESS"
export const SET_JSON_RUN_SETTINGS = "SET_JSON_RUN_SETTINGS"
export const JSON_LOAD_MAP_DATA_SUCCESS = "JSON_LOAD_MAP_DATA_SUCCESS"
export const SET_MAP_DATA_PLOT_PATHS = "SET_MAP_DATA_PLOT_PATHS"
export const SET_JSON_VIDEO_MANIFESTS = "SET_JSON_VIDEO_MANIFESTS"
export const INIT_LOAD_COMPLETE = "INIT_LOAD_COMPLETE"

export const VIDEO_PLAYBACK_UPDATE = "VIDEO_PLAYBACK_UPDATE"
